### ISSUE TITLE
should reject keep message at front of queue?

### ISSUE THREAD

**Issue by jrmurad** [mateodelnorte/servicebus#35] opened 2015-02-27 18:10 UTC
It would help guarantee order when required.

**Comment by mateodelnorte** [comment] 2015-03-10 06:25
So, the retry middleware currently has two means of retying a message - "distributed" and "local". 

"local" means we are going to keep an in-memory representation of the cids of messages that we have rejected and their current retry counts. This is almost always used with some domains or other structured error handling such that an error in the app, or something that would cause a rejection, doesn't crash the app but instead leads to the message reject. If you did crash the app, you'd lose the message retry count hash, and it would have gained you nothing. And it should be said that the only reason we use this retry count has is because 1) you can't modify headers on a message that is requeued when rejected (so you can't tell if a message is being retried for the nth time that way) and 2) putting a message on the *back* of the queue is the only way you'll be able to modify those headers. 

"distributed" just means 'not local'. in the distributed model, we modify the headers and we put the message on the back of the queue - because AFAIK that's the best we can do *if we want to specify a max retry count higher than 1*. 

You've previously discussed using redis or another out of process store to house message retry counts and I think that would be awesome. Refactoring the middleware to simply accept a store - be it a memory store, a redis store, or whatever, would be a great way to get the best of all worlds.

**Comment by mateodelnorte** [comment] 2015-03-11 15:26
Working as designed. Closing this for now, en lieu of a more all-encompassing fix to refactor the retry() middleware to have a message store provider pattern. The pattern will allow you to have a MemoryStore which will track retry counts in memory, or for instance a RedisStore which will track message cids and their associated retry counts in redis.

**Closed by mateodelnorte** 2015-03-11 15:26 UTC
